snake:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 0.1, i: 0.05, d: 0.01}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 0.1, i: 0.05, d: 0.01}